package com.col.notnetmediaforge.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Paleta modo oscuro (diseño principal) ----
val DarkPrimary = Color(0xFF8B7CF6)
val DarkOnPrimary = Color(0xFF1C143A)
val DarkPrimaryContainer = Color(0xFF4C3FA8)
val DarkOnPrimaryContainer = Color(0xFFE8E2FF)
val DarkSecondary = Color(0xFF00E0D6)
val DarkOnSecondary = Color(0xFF003734)
val DarkSecondaryContainer = Color(0xFF00504B)
val DarkOnSecondaryContainer = Color(0xFFA2F2EB)
val DarkTertiary = Color(0xFFFFB3C1)
val DarkOnTertiary = Color(0xFF4A1020)
val DarkTertiaryContainer = Color(0xFF7A2A3B)
val DarkOnTertiaryContainer = Color(0xFFFFD9E0)
val DarkBackground = Color(0xFF0E1015)
val DarkOnBackground = Color(0xFFE6E8EE)
val DarkSurface = Color(0xFF11141B)
val DarkOnSurface = Color(0xFFE6E8EE)
val DarkSurfaceVariant = Color(0xFF1B1E27)
val DarkOnSurfaceVariant = Color(0xFFC2C6D0)
val DarkSurfaceContainer = Color(0xFF1E222C)
val DarkOnSurfaceContainer = Color(0xFFDEE2EA)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkOutline = Color(0xFF8B919E)
val DarkOutlineVariant = Color(0xFF3C414C)

// ---- Paleta modo claro ----
val LightPrimary = Color(0xFF5A4BC0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE8E0FF)
val LightOnPrimaryContainer = Color(0xFF1C006B)
val LightSecondary = Color(0xFF006A64)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF9BF2EA)
val LightOnSecondaryContainer = Color(0xFF00201D)
val LightTertiary = Color(0xFF8C4A5C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD9E0)
val LightOnTertiaryContainer = Color(0xFF3B071B)
val LightBackground = Color(0xFFFDFBFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurface = Color(0xFFFDFBFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFE4E1EC)
val LightOnSurfaceVariant = Color(0xFF47464F)
val LightSurfaceContainer = Color(0xFFF1EDF7)
val LightOnSurfaceContainer = Color(0xFF1F1E24)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightOutline = Color(0xFF777680)
val LightOutlineVariant = Color(0xFFC7C5D0)
